/* Auto-generated by train_svm_mfcc.py � do not edit manually */
#ifndef SVM_PARAMS_H
#define SVM_PARAMS_H

#include "arm_math.h"

#define VECTOR_DIMENSION    26
#define NB_CLASSIFIERS      5

/*
  Class mapping (label -> integer ID):
    'a' -> 0
    'e' -> 1
    'i' -> 2
    'o' -> 3
    'u' -> 4
  Each classifier K outputs:
    classes[0] = K  -> input belongs to class K
    classes[1] = -1 -> input belongs to 'rest'
  Run all classifiers and pick the one that predicts classes[0].
*/

/* --- Classifier 0: 'a' (id=0) vs rest --- */
/*     decision = dot(w, x) + -0.34544949          */
#define NB_SV_A_VS_REST      1
#define INTERCEPT_A_VS_REST  -0.34544949f

/* Dual coefficient: fixed at 1.0 (w is encoded as the support vector) */
const float32_t dualCoefficients_a_vs_rest[] = {
  1.00000000f
};

/* Support vector = weight vector w of the linear hyperplane */
const float32_t supportVectors_a_vs_rest[] = {
  -0.04646004f, 0.06832201f, -0.43156474f, 0.32877790f, 0.91281424f,
  0.37207628f, -0.35877279f, 0.43043926f, 0.20290797f, 0.25352455f,
  -0.10836399f, -0.57571238f, -0.09184259f, -0.00644266f, 0.45897189f,
  -0.45183430f, -0.45778664f, -0.19723771f, -0.18357961f, -0.23386218f,
  0.49759186f, 0.33896505f, -0.08102916f, 0.41629058f, 0.27308295f, 0.17130871f
};

/* Class IDs: [target class, rest sentinel] */
const int32_t classes_a_vs_rest[] = {
  -1, 0x61
};

/* --- Classifier 1: 'e' (id=1) vs rest --- */
/*     decision = dot(w, x) + 0.18314002          */
#define NB_SV_E_VS_REST      1
#define INTERCEPT_E_VS_REST  0.18314002f

/* Dual coefficient: fixed at 1.0 (w is encoded as the support vector) */
const float32_t dualCoefficients_e_vs_rest[] = {
  1.00000000f
};

/* Support vector = weight vector w of the linear hyperplane */
const float32_t supportVectors_e_vs_rest[] = {
  -0.00028367f, -0.35751228f, -0.15135882f, -0.15818431f, -1.35152043f,
  0.11957798f, -0.27890240f, 0.00896659f, 0.23036683f, -0.21277888f,
  0.20230414f, 0.63046063f, 0.06067568f, 0.03867743f, -0.53190262f,
  0.39964533f, 0.61037237f, -0.01948154f, -0.17808215f, 0.06533800f,
  0.06625832f, -0.40959201f, -0.25856497f, -0.25776989f, -0.07238262f,
  -0.28640956f
};

/* Class IDs: [target class, rest sentinel] */
const int32_t classes_e_vs_rest[] = {
  -1, 0x65
};

/* --- Classifier 2: 'i' (id=2) vs rest --- */
/*     decision = dot(w, x) + -1.10337166          */
#define NB_SV_I_VS_REST      1
#define INTERCEPT_I_VS_REST  -1.10337166f

/* Dual coefficient: fixed at 1.0 (w is encoded as the support vector) */
const float32_t dualCoefficients_i_vs_rest[] = {
  1.00000000f
};

/* Support vector = weight vector w of the linear hyperplane */
const float32_t supportVectors_i_vs_rest[] = {
  0.07285799f, -0.39038297f, 0.47498942f, 0.27907878f, 0.91728102f,
  -0.22186153f, 0.34899608f, -0.13895374f, -0.49848695f, -0.46594028f,
  -0.18274711f, -0.16642686f, 0.20802644f, 0.04667851f, 0.03253061f,
  0.23373842f, -0.47348182f, -0.29189118f, -0.18895784f, -0.22631917f,
  -0.39125923f, -0.32542372f, -0.06203227f, -0.22627709f, -0.21661121f,
  -0.05319256f
};

/* Class IDs: [target class, rest sentinel] */
const int32_t classes_i_vs_rest[] = {
  -1, 0x69
};

/* --- Classifier 3: 'o' (id=3) vs rest --- */
/*     decision = dot(w, x) + -0.10965125          */
#define NB_SV_O_VS_REST      1
#define INTERCEPT_O_VS_REST  -0.10965125f

/* Dual coefficient: fixed at 1.0 (w is encoded as the support vector) */
const float32_t dualCoefficients_o_vs_rest[] = {
  1.00000000f
};

/* Support vector = weight vector w of the linear hyperplane */
const float32_t supportVectors_o_vs_rest[] = {
  -0.07358759f, -0.11831552f, -0.15741557f, -0.83295423f, -0.22989139f,
  -0.17261915f, 0.46255416f, -0.03300937f, 0.04227064f, 0.99988848f,
  0.25179298f, -0.12952614f, -0.95273530f, -0.16448019f, -0.07974675f,
  -0.40674939f, 0.43204434f, -0.12457980f, -0.20374756f, 0.10968092f,
  0.05091347f, -0.13890625f, 0.09953426f, 0.00511165f, -0.11273443f,
  -0.07929118f
};

/* Class IDs: [target class, rest sentinel] */
const int32_t classes_o_vs_rest[] = {
  -1, 0x6F
};

/* --- Classifier 4: 'u' (id=4) vs rest --- */
/*     decision = dot(w, x) + -0.73343899          */
#define NB_SV_U_VS_REST      1
#define INTERCEPT_U_VS_REST  -0.73343899f

/* Dual coefficient: fixed at 1.0 (w is encoded as the support vector) */
const float32_t dualCoefficients_u_vs_rest[] = {
  1.00000000f
};

/* Support vector = weight vector w of the linear hyperplane */
const float32_t supportVectors_u_vs_rest[] = {
  -0.10371205f, 0.66527472f, -0.20197764f, 0.91713492f, -0.00430495f,
  -0.23994260f, -0.03857767f, -0.15258953f, -1.04040698f, -0.38548212f,
  -0.51158772f, 0.37492556f, 0.74283128f, -0.23705799f, 0.35257007f,
  0.02378650f, 0.22582126f, -0.19853569f, -0.15066504f, -0.21167422f,
  -0.63304101f, -0.00229402f, -0.10863720f, -0.12095295f, -0.05366853f,
  -0.11189001f
};

/* Class IDs: [target class, rest sentinel] */
const int32_t classes_u_vs_rest[] = {
  -1, 0x75
};

#endif /* SVM_PARAMS_H */
