"""
Trains an SVM model using scikit-learn with labeled MFCC data.
The .npy files must be in the current directory and must have the format mfcc_<label>.npy

Usage:
    python train_svm_mfcc.py

For multiclass with CMSIS-DSP, we explicitly train N independent binary LinearSVC classifiers
(One-vs-Rest), one per class. Each is exported as its own set of C arrays
ready to initialize a separate arm_svm_linear_instance_f32 structure.
"""

import numpy as np
import glob
import sys
from sklearn.svm import LinearSVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

def format_float_array(arr, name, indent=2):
    """Formats a numpy array as a C float32_t array literal."""
    spaces = " " * indent
    items = [f"{v:.8f}f" for v in arr.flatten()]
    lines = []
    line = spaces
    for i, item in enumerate(items):
        addition = item + (", " if i < len(items) - 1 else "")
        if len(line) + len(addition) > 80:
            lines.append(line.rstrip())
            line = spaces + addition
        else:
            line += addition
    if line.strip():
        lines.append(line.rstrip())
    return f"const float32_t {name}[] = {{\n" + "\n".join(lines) + "\n};"


def format_int_array(arr, name, indent=2):
    """Formats an integer array as a C int32_t array literal."""
    spaces = " " * indent
    body = spaces + ", ".join(str(int(v)) for v in arr)
    return f"const int32_t {name}[] = {{\n{body}\n}};"


def export_h_file(ovr_clf, label_to_int, n_features, output_path="svm_params.h"):
    """
    Exports the parameters of the One-vs-Rest LinearSVC binary classifiers as a C header.

    OneVsRestClassifier exposes .estimators_, a list of N fitted LinearSVCs,
    one per class. Each LinearSVC has:
        .coef_        shape: (1, n_features)  — the normal vector of the hyperplane
        .intercept_   shape: (1,)             — the bias term

    arm_svm_linear from CMSIS-DSP uses the dot product formulation:
        decision = dot(dualCoefficients * supportVectors) + intercept
    which is equivalent to:
        decision = dot(w, x) + b
    so we encode the weight vector w as a single "support vector" with
    dual coefficient = 1.0, which gives the same result.
    """
    unique_labels = sorted(label_to_int.keys())
    n_classes     = len(unique_labels)

    guard = "SVM_PARAMS_H"
    lines = []
    lines.append("/* Automatically generated by train_svm_mfcc.py — do not edit manually */")
    lines.append(f"#ifndef {guard}")
    lines.append(f"#define {guard}")
    lines.append("")
    lines.append('#include "arm_math.h"')
    lines.append("")
    lines.append(f"#define VECTOR_DIMENSION    {n_features}")
    lines.append(f"#define NB_CLASSIFIERS      {n_classes}")
    lines.append("")
    lines.append("/*")
    lines.append("  Class mapping (label -> integer ID):")
    for label, idx in label_to_int.items():
        lines.append(f"    '{label}' -> {idx}")
    lines.append("  Each classifier K produces:")
    lines.append("    classes[0] = K  -> input belongs to class K")
    lines.append("    classes[1] = -1 -> input belongs to 'rest'")
    lines.append("  Run all classifiers and choose the one that predicts classes[0].")
    lines.append("*/")
    lines.append("")

    for k, label in enumerate(unique_labels):
        id_k      = label_to_int[label]
        suffix    = f"{label}_vs_rest"
        estimator = ovr_clf.estimators_[k]  # LinearSVC ajustado para esta clase

        # LinearSVC decision: dot(coef_, x) + intercept_
        # We represent this as a single support vector (the weight vector)
        # with a dual coefficient of 1.0, which is mathematically identical.
        w             = estimator.coef_.flatten()        # shape: (n_features,)
        intercept_val = float(estimator.intercept_[0])

        lines.append(f"/* --- Classifier {k}: '{label}' (id={id_k}) vs rest --- */")
        lines.append(f"/*     decision = dot(w, x) + {intercept_val:.8f}          */")
        lines.append(f"#define NB_SV_{suffix.upper()}      1")
        lines.append(f"#define INTERCEPT_{suffix.upper()}  {intercept_val:.8f}f")
        lines.append("")
        lines.append("/* Dual coefficient: fixed at 1.0 (w is encoded as the support vector) */")
        lines.append(format_float_array(np.array([1.0]), f"dualCoefficients_{suffix}"))
        lines.append("")
        lines.append("/* Support vector = weight vector w of the linear hyperplane */")
        lines.append(format_float_array(w, f"supportVectors_{suffix}"))
        lines.append("")
        lines.append(format_int_array([-1, id_k], f"classes_{suffix}"))  # Class IDs: [target class, rest sentinel]
        lines.append("")

    lines.append(f"#endif /* {guard} */")
    lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Header written to: {output_path}")
    for k, label in enumerate(unique_labels):
        print(f"  Classifier {k}: '{label}' vs rest")


def main():
    npy_files = sorted([
        f for f in glob.glob("mfcc_*.npy")
        if not f.endswith("_files.npy")
    ])
    if not npy_files:
        print("No mfcc_*.npy files found in current folder.")
        sys.exit(1)

    all_X      = []
    all_labels = []

    for data_file in npy_files:
        label = data_file.replace("mfcc_", "").replace(".npy", "")
        X = np.load(data_file)

        # Remove first sample (button press noise)
        # Fixed in the serial acquisition script, but just in case,
        # uncomment line below.
        #X = X[1:]

        all_X.append(X)
        all_labels.extend([label] * len(X))
        print(f"Loaded {X.shape[0]} samples for label '{label}'.")

    X_combined = np.vstack(all_X)
    y_combined = np.array(all_labels)
    print(f"Total samples: {X_combined.shape[0]}, features: {X_combined.shape[1]}")

    unique_labels = sorted(set(all_labels))
    label_to_int  = {label: idx for idx, label in enumerate(unique_labels)}
    print("Label mapping:", label_to_int)

    X_train, X_test, y_train, y_test = train_test_split(
        X_combined, y_combined, test_size=0.2, random_state=42, stratify=y_combined
    )

    print("Training OvR linear SVM classifiers...")
    ovr_clf = OneVsRestClassifier(LinearSVC(random_state=42, max_iter=10000), n_jobs=-1)
    ovr_clf.fit(X_train, y_train)

    y_pred = ovr_clf.predict(X_test)
    print(f"Test accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print(classification_report(y_test, y_pred))

    n_features = X_combined.shape[1]
    print(f"\n{len(unique_labels)} classes -> {len(unique_labels)} OvR binary classifiers to export")
    export_h_file(ovr_clf, label_to_int, n_features, output_path="svm_params.h")


if __name__ == "__main__":
    main()